# config.yaml
project_base_dir: '/Users/lee/GitProjects/fork-pointnet2-pytorch/pointnet2'  # 项目根目录的绝对路径
# project_base_dir: 'E:\GitProjects\fork-pointnet2-pytorch\pointnet2'  # 项目根目录的绝对路径


# Mac地址
dataset:
  ModelNet_path: /Users/lee/Datasets/PointCloudsDatasets/modelnet40_normal_resampled/modelnet40_normal_resampled
  # ShapeNet_path: /Volumes/data/Datasets/PointCloudsDatasets/ShapeNet_normal/data/shapenetcore_partanno_segmentation_benchmark_v0_normal
  ShapeNet_path: /Volumes/data/Datasets/PointCloudsDatasets/ShapeNet_normal/data/shapenetcore_partanno_segmentation_benchmark_v0_normal_add_welding_workpiece
  S3DIS_path: /Users/lee/Datasets/PointCloudsDatasets/S3DIS/Stanford3dDataset_v1.2_Aligned_Version

# Windows地址
# dataset:
#   ModelNet_path: /Users/lee/Datasets/PointCloudsDatasets/modelnet40_normal_resampled/modelnet40_normal_resampled
#   ShapeNet_path: F:\shapenetcore_partanno_segmentation_benchmark_v0_normal\data\shapenetcore_partanno_segmentation_benchmark_v0_normal
#   S3DIS_path: /Users/lee/Datasets/PointCloudsDatasets/S3DIS/Stanford3dDataset_v1.2_Aligned_Version

# linux地址
# dataset:
#   ModelNet_path: /root/autodl-fs/datasets/PointcloudData/modelnet40_normal_resampled
#   ShapeNet_path: /root/autodl-fs/datasets/PointcloudData/shapenetcore_partanno_segmentation_benchmark_v0_normal
#   S3DIS_path: /root/autodl-fs/datasets/PointcloudData/Stanford3dDataset_v1.2_Aligned_Version


BASE_INFO_PARTSEG:
  num_classes: 16   # 类别数量
  num_part: 7       # 每个对象可能的分割部分数
  seg_classes:
    # Earphone:
    #   - 16
    #   - 17
    #   - 18
    # Motorbike:
    #   - 30
    #   - 31
    #   - 32
    #   - 33
    #   - 34
    #   - 35
    # Rocket:
    #   - 41
    #   - 42
    #   - 43
    # Car:
    #   - 8
    #   - 9
    #   - 10
    #   - 11
    # Laptop:
    #   - 28
    #   - 29
    # Cap:
    #   - 6
    #   - 7
    # Skateboard:
    #   - 44
    #   - 45
    #   - 46
    # Mug:
    #   - 36
    #   - 37
    # Guitar:
    #   - 19
    #   - 20
    #   - 21
    # Bag:
    #   - 4
    #   - 5
    # Lamp:
    #   - 24
    #   - 25
    #   - 26
    #   - 27
    # Table:
    #   - 47
    #   - 48
    #   - 49
    # Airplane:
    #   - 0
    #   - 1
    #   - 2
    #   - 3
    # Pistol:
    #   - 38
    #   - 39
    #   - 40
    # Chair:
    #   - 12
    #   - 13
    #   - 14
    #   - 15
    # Knife:
    #   - 22
      # - 23
    Workpiece:
      - 0
      - 1
      - 2





